spring:
  application:
    name: promotion-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: "${spring.application.name}"
  tracing:
    enabled: true
    sampling:
      probability: 1.0

app:
  jaeger:
    endpoint: http://localhost:14250