spring:
  application:
    name: promotion-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    jpa:
      repositories:
        enabled: true

server:
  port: 8082
  tomcat:
    fail-on-load-failure: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /actuator/products

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: "${spring.application.name}"

  tracing:
    enabled: true
    sampling:
      probability: 1.0

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway: trace
          gateway.route.RouteDefinitionRouteLocator: info
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"

app:
  jaeger:
    endpoint: http://localhost:14250
